# VEO3 Consistency Generator Configuration
# Production-ready video generation system with continuity tracking

# Project Type
project_type: veo3_video_generator

# Autonomy Mode
autonomy: trusted

# Feature Toggles
features:
  research: true                 # Research VEO3 best practices
  tests: true                    # Validation workflows
  docs: true                     # Documentation generation
  devops: false                  # Not needed for API-focused project
  data: true                     # Video metadata, scene tracking

# VEO3-Specific Configuration
veo3:
  api_key_source: "env"          # Load from .env file
  api_endpoint: "https://generativelanguage.googleapis.com/v1beta/models"
  model: "veo-3"
  consistency_mode: "strict"     # strict | balanced | creative

  # Consistency Controls
  consistency:
    character_tracking: true     # Track character appearance across scenes
    location_tracking: true      # Maintain location consistency
    voice_tracking: true         # Voice consistency (if supported)
    lighting_tracking: true      # Lighting and color consistency
    style_tracking: true         # Visual style consistency

  # Hallucination Reduction
  safeguards:
    prompt_validation: true      # Validate prompts before sending
    reference_checking: true     # Check against reference material
    continuity_validation: true  # Validate scene-to-scene continuity
    max_retries: 3              # Retry failed generations

  # Video Generation Settings
  generation:
    default_duration: 5          # Default video duration in seconds
    resolution: "1080p"
    fps: 24
    aspect_ratio: "16:9"

# MCP Server Configuration
mcp:
  playwright: false              # Not needed for API-only project
  fs: true                       # Filesystem access for video storage
  git: read                      # Read-only git access
  browser: false                 # Web browsing disabled
  jina: auto                     # Auto-enable if key present
  auto_discover: true

# Project Paths
paths:
  src: ./src
  agents: ./src/agents
  utils: ./src/utils
  lib: ./src/lib
  data: ./data
  output: ./output/videos
  metadata: ./data/metadata
  logs: ./.claude/logs
  workdir: ./

# Guardrails
guardrails:
  write_scope:
    - "src/**"
    - "data/**"
    - "docs/**"
    - "tests/**"
    - "output/**"
  protected_files:
    - ".env*"
    - "config.yaml"
    - "package-lock.json"
  require_tests_to_pass: true
  strict_mode: false

# Logging
logging:
  enabled: true
  level: "info"
  run_logs: ".claude/logs/{YYYY-MM-DD}/"
  summaries: ".claude/reports/"
  rotation: true
  max_size: "10MB"
  max_files: 10

# Project Information
project:
  name: "VEO3 Consistency Generator"
  version: "0.1.0"
  description: "Production-ready VEO3 video generator with consistency controls"
  repository: ""

# Agent Configuration
agents:
  # Core agents
  research:
    enabled: true
    definition: ".claude/agents/research.md"
    fallback_mode: "local"

  coder:
    enabled: true
    definition: ".claude/agents/coder.md"

  tester:
    enabled: true
    definition: ".claude/agents/tester.md"

  integrator:
    enabled: true
    definition: ".claude/agents/integrator.md"

  stuck:
    enabled: true
    definition: ".claude/agents/stuck.md"

  # VEO3-Specific Agents
  veo3-prompt-engineer:
    enabled: true
    definition: ".claude/agents/veo3-prompt-engineer.md"
    description: "Crafts consistent prompts for VEO3"

  veo3-continuity-tracker:
    enabled: true
    definition: ".claude/agents/veo3-continuity-tracker.md"
    description: "Tracks scene-to-scene continuity"

  veo3-validator:
    enabled: true
    definition: ".claude/agents/veo3-validator.md"
    description: "Validates outputs and detects hallucinations"

  # Restore Assist Integration
  sop-video-builder:
    enabled: true
    definition: ".claude/agents/sop-video-builder.md"
    description: "Builds SOP videos using Restore Assist methodology"

  # Disable unnecessary agents
  master-fullstack:
    enabled: false

  master-devops:
    enabled: false

  master-docs:
    enabled: true
    definition: ".claude/agents/master-docs.md"
    auto_generate: true

  master-data:
    enabled: false

# Stack Configuration
stack:
  preset: "python_api"
  language: "Python"
  framework: "FastAPI"
  database: "SQLite"           # For metadata storage
  testing: "pytest"
  package_manager: "pip"

# Workflow Templates
workflows:
  generate_video:
    description: "Generate a single consistent video"
    steps:
      - agent: research
        description: "Gather VEO3 API documentation and best practices"
      - agent: veo3-prompt-engineer
        description: "Craft optimized prompt with consistency parameters"
      - agent: coder
        description: "Implement video generation logic"
      - agent: veo3-validator
        description: "Validate output (PHASE GATE)"
      - agent: integrator
        description: "Finalize and store metadata"

  generate_sequence:
    description: "Generate a sequence of related videos"
    steps:
      - agent: research
        description: "Analyze scene sequence requirements"
      - agent: veo3-continuity-tracker
        description: "Initialize continuity tracking"
      - agent: veo3-prompt-engineer
        description: "Generate scene-specific prompts"
      - agent: coder
        description: "Implement sequence generation"
      - agent: veo3-validator
        description: "Validate consistency across scenes (GATE)"
      - agent: integrator
        description: "Compile sequence and metadata"

  fix_hallucination:
    description: "Fix hallucination issues in generated video"
    steps:
      - agent: veo3-validator
        description: "Identify hallucination patterns"
      - agent: stuck
        description: "Analyze root cause"
      - agent: veo3-prompt-engineer
        description: "Refine prompt to reduce hallucination"
      - agent: coder
        description: "Regenerate video"
      - agent: veo3-validator
        description: "Re-validate (GATE)"

  generate_sop_video:
    description: "Generate SOP video using Restore Assist methodology (4×8 second segments)"
    steps:
      - agent: sop-video-builder
        description: "Collect questionnaire and validate requirements"
      - agent: veo3-continuity-tracker
        description: "Initialize continuity baseline"
      - agent: sop-video-builder
        description: "Translate segments to VEO3 prompts"
      - agent: coder
        description: "Generate all 8-second segments"
      - agent: veo3-validator
        description: "Validate each segment (GATE)"
      - agent: integrator
        description: "Compile segments and export for platforms"

# Environment Settings
environments:
  development:
    debug: true
    autonomy: trusted
    require_tests: false

  production:
    debug: false
    autonomy: trusted
    require_tests: true
    require_approval: false
    strict_mode: false

# Phase Gates
phase_gates:
  validator_to_integrator: true  # Validator MUST pass before Integrator
  manual_approval_production: false
